### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by mikekestemont** [JonathanReeve/text-matcher#16]
Thanks for a great package @JonathanReeve ! Any suggestion for how to cite this repo (Bibtex-style)?

**Comment by JonathanReeve** [comment]
Thanks! I imagine it would be something like this: 

```bibtex
@misc{Reeve2020,
  author = {Reeve, Jonathan},
  title = {Text-Matcher},
  year = {2020},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/JonathanReeve/text-matcher}},
  commit = {988d9422a63165225ea136fc31427b1e57814505},
  doi = {10.5281/zenodo.3937738}
}
```
I just added this repo to Zenodo, too, so it should now have a stable DOI. 

I should try to make this more formal, though. I'll add an issue for submitting this to the Journal of Open Source Software.

**Comment by mikekestemont** [comment]
Perfect, thanks! (Closing this.)
