### ISSUE TITLE
Couple fixes

### ISSUE THREAD

**Issue by aizdorovets** [JonathanReeve/text-matcher#23]
Hey mate
Thank you for this lib
However, there are a couple bugs of various problematicity. I think it'd be cool to fix them as they basically require just moving a couple lines around. Idk if you still maintain the lib, but it's really quick and easy

**Comment by JonathanReeve** [comment]
If there are two issues, could you: (1) rename this issue to describe the first issue, making sure the title of this issue is descriptive, and (2) create a second issue which describes the second issue?

**Comment by aizdorovets** [comment]
Opened a PR for both of them. Sorry for a poor issue, that's my first time doing something like this on github, I am nervous :) I'll close this issue for now because of the PR https://github.com/JonathanReeve/text-matcher/pull/24
